# Generated by Django 5.0.3 on 2024-03-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=50),
        ),
    ]
