# Generated by Django 5.0.3 on 2024-03-18 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_student_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
    ]
